/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        /* ── Original Login tokens ── */
        "on-secondary-fixed": "#1b1b1d",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#afc8f0",
        "tertiary-fixed-dim": "#c0c7cc",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "error-red": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "tertiary": "#02070a",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#161d20",
        "secondary-container": "#58a6ff",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#004882",
        "background": "#f7f9fb",
        "on-primary-fixed": "#001c3a",
        "tertiary-container": "#192024",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#41484c",
        "surface": "#f7f9fb",
        "secondary-fixed": "#d3e4ff",
        "surface-dim": "#d8dadc",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#80888c",
        "outline-variant": "#c4c6cf",
        "on-primary-container": "#6f88ad",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#afc8f0",
        "secondary-fixed-dim": "#a2c9ff",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        "surface-tint": "#476083",
        "on-secondary-container": "#003a6b",
        "outline": "#74777f",
        "on-surface-variant": "#43474e",
        "on-primary-fixed-variant": "#2f486a",
        "primary-fixed": "#d4e3ff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#dce3e8",
        "on-background": "#191c1e",
        "navy": "#0f2747",
        "navy-hover": "#1e3a8a",
        "primary": "#0f2747",
        "secondary": "#0060aa",
        "primary-container": "#001f3f",
        "on-secondary-fixed": "#001c38",
        "on-tertiary-fixed-variant": "#41484c",
        "on-primary-fixed-variant": "#2f486a",
        "secondary-fixed-dim": "#a2c9ff",
        "on-secondary-fixed-variant": "#004882",
        "on-tertiary-fixed": "#161d20",
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "card": "1.75rem",
        "input": "0.75rem",
        "full": "9999px"
      },
      "boxShadow": {
        "card": "0 1px 2px rgba(15, 39, 71, 0.06), 0 8px 24px rgba(15, 39, 71, 0.08)"
      },
      "spacing": {
        "stack-lg": "32px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "margin-desktop": "48px",
        "gutter": "24px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "unit": "8px",
        "container-padding": "64px"
      },
      "fontFamily": {
        "body-md": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "button": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "label-md": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "display-lg-mobile": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "display-lg": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "button": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "800" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
  corePlugins: {
    preflight: false, // Disable preflight so it doesn't mess up our custom Login.jsx CSS
  }
}
