"""add conditional rules

Revision ID: 20aec71df882
Revises: 5fb0d0af5095
Create Date: 2026-08-19 17:59:01.493790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20aec71df882'
down_revision: Union[str, Sequence[str], None] = '5fb0d0af5095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conditional_rules_form_id'), table_name='conditional_rules')
    op.drop_index(op.f('ix_conditional_rules_id'), table_name='conditional_rules')
    op.drop_table('conditional_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditional_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trigger_field_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition_operator', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('comparison_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_field_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('conditional_rules_pkey'))
    )
    op.create_index(op.f('ix_conditional_rules_id'), 'conditional_rules', ['id'], unique=False)
    op.create_index(op.f('ix_conditional_rules_form_id'), 'conditional_rules', ['form_id'], unique=False)
    # ### end Alembic commands ###
