"""add publication pdf fields

Revision ID: 5fb0d0af5095
Revises: 4b442ff4432f
Create Date: 2026-08-19 17:37:08.756960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb0d0af5095'
down_revision: Union[str, Sequence[str], None] = '4b442ff4432f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('pdf_filename', sa.String(length=255), nullable=True))
    op.add_column('publications', sa.Column('pdf_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'pdf_path')
    op.drop_column('publications', 'pdf_filename')
    # ### end Alembic commands ###
