/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppConferencesRouteImport } from './routes/_app.conferences'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppNetworkRouteImport } from './routes/_app.network'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppPublicationsRouteImport } from './routes/_app.publications'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppResearchersRouteImport } from './routes/_app.researchers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConferencesRoute = AppConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicationsRoute = AppPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchersRoute = AppResearchersRouteImport.update({
  id: '/researchers',
  path: '/researchers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conferences': typeof AppConferencesRoute
  '/dashboard': typeof AppDashboardRoute
  '/network': typeof AppNetworkRoute
  '/projects': typeof AppProjectsRoute
  '/publications': typeof AppPublicationsRoute
  '/reports': typeof AppReportsRoute
  '/researchers': typeof AppResearchersRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conferences': typeof AppConferencesRoute
  '/dashboard': typeof AppDashboardRoute
  '/network': typeof AppNetworkRoute
  '/projects': typeof AppProjectsRoute
  '/publications': typeof AppPublicationsRoute
  '/reports': typeof AppReportsRoute
  '/researchers': typeof AppResearchersRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/conferences': typeof AppConferencesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/publications': typeof AppPublicationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/researchers': typeof AppResearchersRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conferences'
    | '/dashboard'
    | '/network'
    | '/projects'
    | '/publications'
    | '/reports'
    | '/researchers'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conferences'
    | '/dashboard'
    | '/network'
    | '/projects'
    | '/publications'
    | '/reports'
    | '/researchers'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/conferences'
    | '/_app/dashboard'
    | '/_app/network'
    | '/_app/projects'
    | '/_app/publications'
    | '/_app/reports'
    | '/_app/researchers'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/conferences': {
      id: '/_app/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof AppConferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publications': {
      id: '/_app/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof AppPublicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/researchers': {
      id: '/_app/researchers'
      path: '/researchers'
      fullPath: '/researchers'
      preLoaderRoute: typeof AppResearchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConferencesRoute: typeof AppConferencesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppPublicationsRoute: typeof AppPublicationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResearchersRoute: typeof AppResearchersRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConferencesRoute: AppConferencesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppPublicationsRoute: AppPublicationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppResearchersRoute: AppResearchersRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
